//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlykhachhang
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtincanhan
    {
        public Nullable<int> ID { get; set; }
        public int SoTB { get; set; }
        public string Hoten { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public string Tinh { get; set; }
        public string Huyen { get; set; }
        public string Xa { get; set; }
    }
}
