//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace danhbadienthoai
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        public string tenkhachhang { get; set; }
        public string tencongty { get; set; }
        public string tenlienlac { get; set; }
        public string thongtinlienlac { get; set; }
        public string diachinha { get; set; }
        public string thanhpho { get; set; }
        public string quocgia { get; set; }
        public Nullable<int> sdt { get; set; }
    
        public virtual thongtincanhan thongtincanhan { get; set; }
    }
}
