//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace danhbadienthoai
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class danhbaEntities : DbContext
    {
        public danhbaEntities()
            : base("name=danhbaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dangnhap> dangnhaps { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<thongtincanhan> thongtincanhans { get; set; }
        public virtual DbSet<thongtinnhanvien> thongtinnhanviens { get; set; }
        public virtual DbSet<chucvu> chucvus { get; set; }
    
        public virtual ObjectResult<cn_timkiem_thongtincanhan_Result> cn_timkiem_thongtincanhan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cn_timkiem_thongtincanhan_Result>("cn_timkiem_thongtincanhan");
        }
    
        public virtual int danhba_update_thongtin(Nullable<int> varID, Nullable<int> varSdt, string varHoten, string varTinh, string varHuyen, string varXa, Nullable<bool> varGioitinh, Nullable<System.DateTime> varngay)
        {
            var varIDParameter = varID.HasValue ?
                new ObjectParameter("varID", varID) :
                new ObjectParameter("varID", typeof(int));
    
            var varSdtParameter = varSdt.HasValue ?
                new ObjectParameter("varSdt", varSdt) :
                new ObjectParameter("varSdt", typeof(int));
    
            var varHotenParameter = varHoten != null ?
                new ObjectParameter("varHoten", varHoten) :
                new ObjectParameter("varHoten", typeof(string));
    
            var varTinhParameter = varTinh != null ?
                new ObjectParameter("varTinh", varTinh) :
                new ObjectParameter("varTinh", typeof(string));
    
            var varHuyenParameter = varHuyen != null ?
                new ObjectParameter("varHuyen", varHuyen) :
                new ObjectParameter("varHuyen", typeof(string));
    
            var varXaParameter = varXa != null ?
                new ObjectParameter("varXa", varXa) :
                new ObjectParameter("varXa", typeof(string));
    
            var varGioitinhParameter = varGioitinh.HasValue ?
                new ObjectParameter("varGioitinh", varGioitinh) :
                new ObjectParameter("varGioitinh", typeof(bool));
    
            var varngayParameter = varngay.HasValue ?
                new ObjectParameter("varngay", varngay) :
                new ObjectParameter("varngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("danhba_update_thongtin", varIDParameter, varSdtParameter, varHotenParameter, varTinhParameter, varHuyenParameter, varXaParameter, varGioitinhParameter, varngayParameter);
        }
    
        public virtual int danhba_update_thongtincanhan(Nullable<int> varID, Nullable<int> varSdt, string varHoten, string varTinh, string varHuyen, string varXa, Nullable<bool> varGioitinh)
        {
            var varIDParameter = varID.HasValue ?
                new ObjectParameter("varID", varID) :
                new ObjectParameter("varID", typeof(int));
    
            var varSdtParameter = varSdt.HasValue ?
                new ObjectParameter("varSdt", varSdt) :
                new ObjectParameter("varSdt", typeof(int));
    
            var varHotenParameter = varHoten != null ?
                new ObjectParameter("varHoten", varHoten) :
                new ObjectParameter("varHoten", typeof(string));
    
            var varTinhParameter = varTinh != null ?
                new ObjectParameter("varTinh", varTinh) :
                new ObjectParameter("varTinh", typeof(string));
    
            var varHuyenParameter = varHuyen != null ?
                new ObjectParameter("varHuyen", varHuyen) :
                new ObjectParameter("varHuyen", typeof(string));
    
            var varXaParameter = varXa != null ?
                new ObjectParameter("varXa", varXa) :
                new ObjectParameter("varXa", typeof(string));
    
            var varGioitinhParameter = varGioitinh.HasValue ?
                new ObjectParameter("varGioitinh", varGioitinh) :
                new ObjectParameter("varGioitinh", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("danhba_update_thongtincanhan", varIDParameter, varSdtParameter, varHotenParameter, varTinhParameter, varHuyenParameter, varXaParameter, varGioitinhParameter);
        }
    
        public virtual ObjectResult<db_Searchthongtincanhan_Hoten_Result> db_Searchthongtincanhan_Hoten(string vHoten)
        {
            var vHotenParameter = vHoten != null ?
                new ObjectParameter("vHoten", vHoten) :
                new ObjectParameter("vHoten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<db_Searchthongtincanhan_Hoten_Result>("db_Searchthongtincanhan_Hoten", vHotenParameter);
        }
    
        public virtual ObjectResult<db_Searchthongtincanhan_SDT_Result> db_Searchthongtincanhan_SDT(Nullable<int> vSdt)
        {
            var vSdtParameter = vSdt.HasValue ?
                new ObjectParameter("vSdt", vSdt) :
                new ObjectParameter("vSdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<db_Searchthongtincanhan_SDT_Result>("db_Searchthongtincanhan_SDT", vSdtParameter);
        }
    
        public virtual ObjectResult<getalldanhba_Result> getalldanhba()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getalldanhba_Result>("getalldanhba");
        }
    
        public virtual ObjectResult<getallkhachhang_Result> getallkhachhang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallkhachhang_Result>("getallkhachhang");
        }
    
        public virtual ObjectResult<Procedure_thongtin_Result> Procedure_thongtin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Procedure_thongtin_Result>("Procedure_thongtin");
        }
    
        public virtual ObjectResult<seaechthongtincanhan_nn_Result> seaechthongtincanhan_nn(string vHoten)
        {
            var vHotenParameter = vHoten != null ?
                new ObjectParameter("vHoten", vHoten) :
                new ObjectParameter("vHoten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seaechthongtincanhan_nn_Result>("seaechthongtincanhan_nn", vHotenParameter);
        }
    
        public virtual int search_thongtincanhan(Nullable<int> vID, Nullable<int> vSdt, string vHoten, string vTinh, string vHuyen, string vXa, Nullable<bool> vGiotinh, Nullable<System.DateTime> vngay)
        {
            var vIDParameter = vID.HasValue ?
                new ObjectParameter("vID", vID) :
                new ObjectParameter("vID", typeof(int));
    
            var vSdtParameter = vSdt.HasValue ?
                new ObjectParameter("vSdt", vSdt) :
                new ObjectParameter("vSdt", typeof(int));
    
            var vHotenParameter = vHoten != null ?
                new ObjectParameter("vHoten", vHoten) :
                new ObjectParameter("vHoten", typeof(string));
    
            var vTinhParameter = vTinh != null ?
                new ObjectParameter("vTinh", vTinh) :
                new ObjectParameter("vTinh", typeof(string));
    
            var vHuyenParameter = vHuyen != null ?
                new ObjectParameter("vHuyen", vHuyen) :
                new ObjectParameter("vHuyen", typeof(string));
    
            var vXaParameter = vXa != null ?
                new ObjectParameter("vXa", vXa) :
                new ObjectParameter("vXa", typeof(string));
    
            var vGiotinhParameter = vGiotinh.HasValue ?
                new ObjectParameter("vGiotinh", vGiotinh) :
                new ObjectParameter("vGiotinh", typeof(bool));
    
            var vngayParameter = vngay.HasValue ?
                new ObjectParameter("vngay", vngay) :
                new ObjectParameter("vngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("search_thongtincanhan", vIDParameter, vSdtParameter, vHotenParameter, vTinhParameter, vHuyenParameter, vXaParameter, vGiotinhParameter, vngayParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_InsertThongtincanhan(Nullable<int> vID, Nullable<int> vSdt, string vHoten, string vTinh, string vHuyen, string vXa, Nullable<bool> vGiotinh, Nullable<System.DateTime> vngay)
        {
            var vIDParameter = vID.HasValue ?
                new ObjectParameter("vID", vID) :
                new ObjectParameter("vID", typeof(int));
    
            var vSdtParameter = vSdt.HasValue ?
                new ObjectParameter("vSdt", vSdt) :
                new ObjectParameter("vSdt", typeof(int));
    
            var vHotenParameter = vHoten != null ?
                new ObjectParameter("vHoten", vHoten) :
                new ObjectParameter("vHoten", typeof(string));
    
            var vTinhParameter = vTinh != null ?
                new ObjectParameter("vTinh", vTinh) :
                new ObjectParameter("vTinh", typeof(string));
    
            var vHuyenParameter = vHuyen != null ?
                new ObjectParameter("vHuyen", vHuyen) :
                new ObjectParameter("vHuyen", typeof(string));
    
            var vXaParameter = vXa != null ?
                new ObjectParameter("vXa", vXa) :
                new ObjectParameter("vXa", typeof(string));
    
            var vGiotinhParameter = vGiotinh.HasValue ?
                new ObjectParameter("vGiotinh", vGiotinh) :
                new ObjectParameter("vGiotinh", typeof(bool));
    
            var vngayParameter = vngay.HasValue ?
                new ObjectParameter("vngay", vngay) :
                new ObjectParameter("vngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertThongtincanhan", vIDParameter, vSdtParameter, vHotenParameter, vTinhParameter, vHuyenParameter, vXaParameter, vGiotinhParameter, vngayParameter);
        }
    
        public virtual int SP_InsertThongtincanhan_1(Nullable<int> vID, Nullable<int> vSdt, string vHoten, string vTinh, string vHuyen, string vXa, Nullable<bool> vGiotinh)
        {
            var vIDParameter = vID.HasValue ?
                new ObjectParameter("vID", vID) :
                new ObjectParameter("vID", typeof(int));
    
            var vSdtParameter = vSdt.HasValue ?
                new ObjectParameter("vSdt", vSdt) :
                new ObjectParameter("vSdt", typeof(int));
    
            var vHotenParameter = vHoten != null ?
                new ObjectParameter("vHoten", vHoten) :
                new ObjectParameter("vHoten", typeof(string));
    
            var vTinhParameter = vTinh != null ?
                new ObjectParameter("vTinh", vTinh) :
                new ObjectParameter("vTinh", typeof(string));
    
            var vHuyenParameter = vHuyen != null ?
                new ObjectParameter("vHuyen", vHuyen) :
                new ObjectParameter("vHuyen", typeof(string));
    
            var vXaParameter = vXa != null ?
                new ObjectParameter("vXa", vXa) :
                new ObjectParameter("vXa", typeof(string));
    
            var vGiotinhParameter = vGiotinh.HasValue ?
                new ObjectParameter("vGiotinh", vGiotinh) :
                new ObjectParameter("vGiotinh", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertThongtincanhan_1", vIDParameter, vSdtParameter, vHotenParameter, vTinhParameter, vHuyenParameter, vXaParameter, vGiotinhParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SP_Xoahongtincanhan(Nullable<int> vID)
        {
            var vIDParameter = vID.HasValue ?
                new ObjectParameter("vID", vID) :
                new ObjectParameter("vID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Xoahongtincanhan", vIDParameter);
        }
    
        public virtual ObjectResult<thongtin_Result> thongtin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongtin_Result>("thongtin");
        }
    
        public virtual ObjectResult<thongkekhuvu_tinh_huyen_Result> thongkekhuvu_tinh_huyen(Nullable<int> vID, Nullable<int> vSdt, string vHoten, string vtinh, string vhuyen)
        {
            var vIDParameter = vID.HasValue ?
                new ObjectParameter("vID", vID) :
                new ObjectParameter("vID", typeof(int));
    
            var vSdtParameter = vSdt.HasValue ?
                new ObjectParameter("vSdt", vSdt) :
                new ObjectParameter("vSdt", typeof(int));
    
            var vHotenParameter = vHoten != null ?
                new ObjectParameter("vHoten", vHoten) :
                new ObjectParameter("vHoten", typeof(string));
    
            var vtinhParameter = vtinh != null ?
                new ObjectParameter("vtinh", vtinh) :
                new ObjectParameter("vtinh", typeof(string));
    
            var vhuyenParameter = vhuyen != null ?
                new ObjectParameter("vhuyen", vhuyen) :
                new ObjectParameter("vhuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkekhuvu_tinh_huyen_Result>("thongkekhuvu_tinh_huyen", vIDParameter, vSdtParameter, vHotenParameter, vtinhParameter, vhuyenParameter);
        }
    
        public virtual ObjectResult<thongke_Result> thongke()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongke_Result>("thongke");
        }
    
        public virtual ObjectResult<Nullable<int>> demsoluong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("demsoluong");
        }
    }
}
