//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace danhbadienthoai
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtinnhanvien
    {
        public Nullable<int> manhanvien { get; set; }
        public string tennhanvien { get; set; }
        public string diachi { get; set; }
        public int sdt { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string email { get; set; }
    }
}
